-- Run this once in Supabase Studio (SQL Editor) for project
-- https://ltxqagtohxzjfrztbbdq.supabase.co
--
-- Creates the `kana_db` table (hiragana/katakana, read-only from the
-- browser) and seeds it with the full standard gojuon table (清音 + 濁音 +
-- 半濁音 + 拗音, 104 mora x 2 kana types = 208 rows).
--
-- The insert rows below are auto-generated from src/lib/kanaSeedData.ts --
-- if that file ever changes, regenerate this block from it rather than
-- hand-editing rows here.

create table if not exists public.kana_db (
  id bigint generated always as identity primary key,
  character text not null,
  kana_type text not null check (kana_type in ('hiragana', 'katakana')),
  romaji text not null,
  group_name text not null,
  sort_order int not null
);

alter table public.kana_db enable row level security;

drop policy if exists "public read" on public.kana_db;
create policy "public read"
  on public.kana_db
  for select
  to anon, authenticated
  using (true);

-- Idempotent: safe to re-run without creating duplicate rows.
delete from public.kana_db;

insert into kana_db (character, kana_type, romaji, group_name, sort_order) values
  ('あ', 'hiragana', 'a', 'あ行', 0),
  ('い', 'hiragana', 'i', 'あ行', 1),
  ('う', 'hiragana', 'u', 'あ行', 2),
  ('え', 'hiragana', 'e', 'あ行', 3),
  ('お', 'hiragana', 'o', 'あ行', 4),
  ('か', 'hiragana', 'ka', 'か行', 5),
  ('き', 'hiragana', 'ki', 'か行', 6),
  ('く', 'hiragana', 'ku', 'か行', 7),
  ('け', 'hiragana', 'ke', 'か行', 8),
  ('こ', 'hiragana', 'ko', 'か行', 9),
  ('さ', 'hiragana', 'sa', 'さ行', 10),
  ('し', 'hiragana', 'shi', 'さ行', 11),
  ('す', 'hiragana', 'su', 'さ行', 12),
  ('せ', 'hiragana', 'se', 'さ行', 13),
  ('そ', 'hiragana', 'so', 'さ行', 14),
  ('た', 'hiragana', 'ta', 'た行', 15),
  ('ち', 'hiragana', 'chi', 'た行', 16),
  ('つ', 'hiragana', 'tsu', 'た行', 17),
  ('て', 'hiragana', 'te', 'た行', 18),
  ('と', 'hiragana', 'to', 'た行', 19),
  ('な', 'hiragana', 'na', 'な行', 20),
  ('に', 'hiragana', 'ni', 'な行', 21),
  ('ぬ', 'hiragana', 'nu', 'な行', 22),
  ('ね', 'hiragana', 'ne', 'な行', 23),
  ('の', 'hiragana', 'no', 'な行', 24),
  ('は', 'hiragana', 'ha', 'は行', 25),
  ('ひ', 'hiragana', 'hi', 'は行', 26),
  ('ふ', 'hiragana', 'fu', 'は行', 27),
  ('へ', 'hiragana', 'he', 'は行', 28),
  ('ほ', 'hiragana', 'ho', 'は行', 29),
  ('ま', 'hiragana', 'ma', 'ま行', 30),
  ('み', 'hiragana', 'mi', 'ま行', 31),
  ('む', 'hiragana', 'mu', 'ま行', 32),
  ('め', 'hiragana', 'me', 'ま行', 33),
  ('も', 'hiragana', 'mo', 'ま行', 34),
  ('や', 'hiragana', 'ya', 'や行', 35),
  ('ゆ', 'hiragana', 'yu', 'や行', 36),
  ('よ', 'hiragana', 'yo', 'や行', 37),
  ('ら', 'hiragana', 'ra', 'ら行', 38),
  ('り', 'hiragana', 'ri', 'ら行', 39),
  ('る', 'hiragana', 'ru', 'ら行', 40),
  ('れ', 'hiragana', 're', 'ら行', 41),
  ('ろ', 'hiragana', 'ro', 'ら行', 42),
  ('わ', 'hiragana', 'wa', 'わ行', 43),
  ('を', 'hiragana', 'wo', 'わ行', 44),
  ('ん', 'hiragana', 'n', 'ん', 45),
  ('が', 'hiragana', 'ga', 'が行', 46),
  ('ぎ', 'hiragana', 'gi', 'が行', 47),
  ('ぐ', 'hiragana', 'gu', 'が行', 48),
  ('げ', 'hiragana', 'ge', 'が行', 49),
  ('ご', 'hiragana', 'go', 'が行', 50),
  ('ざ', 'hiragana', 'za', 'ざ行', 51),
  ('じ', 'hiragana', 'ji', 'ざ行', 52),
  ('ず', 'hiragana', 'zu', 'ざ行', 53),
  ('ぜ', 'hiragana', 'ze', 'ざ行', 54),
  ('ぞ', 'hiragana', 'zo', 'ざ行', 55),
  ('だ', 'hiragana', 'da', 'だ行', 56),
  ('ぢ', 'hiragana', 'di', 'だ行', 57),
  ('づ', 'hiragana', 'du', 'だ行', 58),
  ('で', 'hiragana', 'de', 'だ行', 59),
  ('ど', 'hiragana', 'do', 'だ行', 60),
  ('ば', 'hiragana', 'ba', 'ば行', 61),
  ('び', 'hiragana', 'bi', 'ば行', 62),
  ('ぶ', 'hiragana', 'bu', 'ば行', 63),
  ('べ', 'hiragana', 'be', 'ば行', 64),
  ('ぼ', 'hiragana', 'bo', 'ば行', 65),
  ('ぱ', 'hiragana', 'pa', 'ぱ行', 66),
  ('ぴ', 'hiragana', 'pi', 'ぱ行', 67),
  ('ぷ', 'hiragana', 'pu', 'ぱ行', 68),
  ('ぺ', 'hiragana', 'pe', 'ぱ行', 69),
  ('ぽ', 'hiragana', 'po', 'ぱ行', 70),
  ('きゃ', 'hiragana', 'kya', 'きゃ行', 71),
  ('きゅ', 'hiragana', 'kyu', 'きゃ行', 72),
  ('きょ', 'hiragana', 'kyo', 'きゃ行', 73),
  ('ぎゃ', 'hiragana', 'gya', 'ぎゃ行', 74),
  ('ぎゅ', 'hiragana', 'gyu', 'ぎゃ行', 75),
  ('ぎょ', 'hiragana', 'gyo', 'ぎゃ行', 76),
  ('しゃ', 'hiragana', 'sha', 'しゃ行', 77),
  ('しゅ', 'hiragana', 'shu', 'しゃ行', 78),
  ('しょ', 'hiragana', 'sho', 'しゃ行', 79),
  ('じゃ', 'hiragana', 'ja', 'じゃ行', 80),
  ('じゅ', 'hiragana', 'ju', 'じゃ行', 81),
  ('じょ', 'hiragana', 'jo', 'じゃ行', 82),
  ('ちゃ', 'hiragana', 'cha', 'ちゃ行', 83),
  ('ちゅ', 'hiragana', 'chu', 'ちゃ行', 84),
  ('ちょ', 'hiragana', 'cho', 'ちゃ行', 85),
  ('にゃ', 'hiragana', 'nya', 'にゃ行', 86),
  ('にゅ', 'hiragana', 'nyu', 'にゃ行', 87),
  ('にょ', 'hiragana', 'nyo', 'にゃ行', 88),
  ('ひゃ', 'hiragana', 'hya', 'ひゃ行', 89),
  ('ひゅ', 'hiragana', 'hyu', 'ひゃ行', 90),
  ('ひょ', 'hiragana', 'hyo', 'ひゃ行', 91),
  ('びゃ', 'hiragana', 'bya', 'びゃ行', 92),
  ('びゅ', 'hiragana', 'byu', 'びゃ行', 93),
  ('びょ', 'hiragana', 'byo', 'びゃ行', 94),
  ('ぴゃ', 'hiragana', 'pya', 'ぴゃ行', 95),
  ('ぴゅ', 'hiragana', 'pyu', 'ぴゃ行', 96),
  ('ぴょ', 'hiragana', 'pyo', 'ぴゃ行', 97),
  ('みゃ', 'hiragana', 'mya', 'みゃ行', 98),
  ('みゅ', 'hiragana', 'myu', 'みゃ行', 99),
  ('みょ', 'hiragana', 'myo', 'みゃ行', 100),
  ('りゃ', 'hiragana', 'rya', 'りゃ行', 101),
  ('りゅ', 'hiragana', 'ryu', 'りゃ行', 102),
  ('りょ', 'hiragana', 'ryo', 'りゃ行', 103),
  ('ア', 'katakana', 'a', 'あ行', 0),
  ('イ', 'katakana', 'i', 'あ行', 1),
  ('ウ', 'katakana', 'u', 'あ行', 2),
  ('エ', 'katakana', 'e', 'あ行', 3),
  ('オ', 'katakana', 'o', 'あ行', 4),
  ('カ', 'katakana', 'ka', 'か行', 5),
  ('キ', 'katakana', 'ki', 'か行', 6),
  ('ク', 'katakana', 'ku', 'か行', 7),
  ('ケ', 'katakana', 'ke', 'か行', 8),
  ('コ', 'katakana', 'ko', 'か行', 9),
  ('サ', 'katakana', 'sa', 'さ行', 10),
  ('シ', 'katakana', 'shi', 'さ行', 11),
  ('ス', 'katakana', 'su', 'さ行', 12),
  ('セ', 'katakana', 'se', 'さ行', 13),
  ('ソ', 'katakana', 'so', 'さ行', 14),
  ('タ', 'katakana', 'ta', 'た行', 15),
  ('チ', 'katakana', 'chi', 'た行', 16),
  ('ツ', 'katakana', 'tsu', 'た行', 17),
  ('テ', 'katakana', 'te', 'た行', 18),
  ('ト', 'katakana', 'to', 'た行', 19),
  ('ナ', 'katakana', 'na', 'な行', 20),
  ('ニ', 'katakana', 'ni', 'な行', 21),
  ('ヌ', 'katakana', 'nu', 'な行', 22),
  ('ネ', 'katakana', 'ne', 'な行', 23),
  ('ノ', 'katakana', 'no', 'な行', 24),
  ('ハ', 'katakana', 'ha', 'は行', 25),
  ('ヒ', 'katakana', 'hi', 'は行', 26),
  ('フ', 'katakana', 'fu', 'は行', 27),
  ('ヘ', 'katakana', 'he', 'は行', 28),
  ('ホ', 'katakana', 'ho', 'は行', 29),
  ('マ', 'katakana', 'ma', 'ま行', 30),
  ('ミ', 'katakana', 'mi', 'ま行', 31),
  ('ム', 'katakana', 'mu', 'ま行', 32),
  ('メ', 'katakana', 'me', 'ま行', 33),
  ('モ', 'katakana', 'mo', 'ま行', 34),
  ('ヤ', 'katakana', 'ya', 'や行', 35),
  ('ユ', 'katakana', 'yu', 'や行', 36),
  ('ヨ', 'katakana', 'yo', 'や行', 37),
  ('ラ', 'katakana', 'ra', 'ら行', 38),
  ('リ', 'katakana', 'ri', 'ら行', 39),
  ('ル', 'katakana', 'ru', 'ら行', 40),
  ('レ', 'katakana', 're', 'ら行', 41),
  ('ロ', 'katakana', 'ro', 'ら行', 42),
  ('ワ', 'katakana', 'wa', 'わ行', 43),
  ('ヲ', 'katakana', 'wo', 'わ行', 44),
  ('ン', 'katakana', 'n', 'ん', 45),
  ('ガ', 'katakana', 'ga', 'が行', 46),
  ('ギ', 'katakana', 'gi', 'が行', 47),
  ('グ', 'katakana', 'gu', 'が行', 48),
  ('ゲ', 'katakana', 'ge', 'が行', 49),
  ('ゴ', 'katakana', 'go', 'が行', 50),
  ('ザ', 'katakana', 'za', 'ざ行', 51),
  ('ジ', 'katakana', 'ji', 'ざ行', 52),
  ('ズ', 'katakana', 'zu', 'ざ行', 53),
  ('ゼ', 'katakana', 'ze', 'ざ行', 54),
  ('ゾ', 'katakana', 'zo', 'ざ行', 55),
  ('ダ', 'katakana', 'da', 'だ行', 56),
  ('ヂ', 'katakana', 'di', 'だ行', 57),
  ('ヅ', 'katakana', 'du', 'だ行', 58),
  ('デ', 'katakana', 'de', 'だ行', 59),
  ('ド', 'katakana', 'do', 'だ行', 60),
  ('バ', 'katakana', 'ba', 'ば行', 61),
  ('ビ', 'katakana', 'bi', 'ば行', 62),
  ('ブ', 'katakana', 'bu', 'ば行', 63),
  ('ベ', 'katakana', 'be', 'ば行', 64),
  ('ボ', 'katakana', 'bo', 'ば行', 65),
  ('パ', 'katakana', 'pa', 'ぱ行', 66),
  ('ピ', 'katakana', 'pi', 'ぱ行', 67),
  ('プ', 'katakana', 'pu', 'ぱ行', 68),
  ('ペ', 'katakana', 'pe', 'ぱ行', 69),
  ('ポ', 'katakana', 'po', 'ぱ行', 70),
  ('キャ', 'katakana', 'kya', 'きゃ行', 71),
  ('キュ', 'katakana', 'kyu', 'きゃ行', 72),
  ('キョ', 'katakana', 'kyo', 'きゃ行', 73),
  ('ギャ', 'katakana', 'gya', 'ぎゃ行', 74),
  ('ギュ', 'katakana', 'gyu', 'ぎゃ行', 75),
  ('ギョ', 'katakana', 'gyo', 'ぎゃ行', 76),
  ('シャ', 'katakana', 'sha', 'しゃ行', 77),
  ('シュ', 'katakana', 'shu', 'しゃ行', 78),
  ('ショ', 'katakana', 'sho', 'しゃ行', 79),
  ('ジャ', 'katakana', 'ja', 'じゃ行', 80),
  ('ジュ', 'katakana', 'ju', 'じゃ行', 81),
  ('ジョ', 'katakana', 'jo', 'じゃ行', 82),
  ('チャ', 'katakana', 'cha', 'ちゃ行', 83),
  ('チュ', 'katakana', 'chu', 'ちゃ行', 84),
  ('チョ', 'katakana', 'cho', 'ちゃ行', 85),
  ('ニャ', 'katakana', 'nya', 'にゃ行', 86),
  ('ニュ', 'katakana', 'nyu', 'にゃ行', 87),
  ('ニョ', 'katakana', 'nyo', 'にゃ行', 88),
  ('ヒャ', 'katakana', 'hya', 'ひゃ行', 89),
  ('ヒュ', 'katakana', 'hyu', 'ひゃ行', 90),
  ('ヒョ', 'katakana', 'hyo', 'ひゃ行', 91),
  ('ビャ', 'katakana', 'bya', 'びゃ行', 92),
  ('ビュ', 'katakana', 'byu', 'びゃ行', 93),
  ('ビョ', 'katakana', 'byo', 'びゃ行', 94),
  ('ピャ', 'katakana', 'pya', 'ぴゃ行', 95),
  ('ピュ', 'katakana', 'pyu', 'ぴゃ行', 96),
  ('ピョ', 'katakana', 'pyo', 'ぴゃ行', 97),
  ('ミャ', 'katakana', 'mya', 'みゃ行', 98),
  ('ミュ', 'katakana', 'myu', 'みゃ行', 99),
  ('ミョ', 'katakana', 'myo', 'みゃ行', 100),
  ('リャ', 'katakana', 'rya', 'りゃ行', 101),
  ('リュ', 'katakana', 'ryu', 'りゃ行', 102),
  ('リョ', 'katakana', 'ryo', 'りゃ行', 103);
