// scripts/bump-version.mjs
//
// Runs automatically before `npm run build` (see package.json "prebuild").
// Reads version.json, bumps the minor number by 0.1 on every production
// build, and writes the result to src/lib/version.generated.ts so the
// footer can display it without any server-side code.
//
// Run with --no-bump (used by `npm run dev`) to regenerate the generated
// file WITHOUT incrementing the counter, so local dev doesn't burn through
// version numbers every time you start the dev server.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, "..");
const versionFilePath = join(rootDir, "version.json");
const generatedDir = join(rootDir, "src", "lib");
const generatedFilePath = join(generatedDir, "version.generated.ts");

const noBump = process.argv.includes("--no-bump");

function readVersion() {
  try {
    const raw = readFileSync(versionFilePath, "utf-8");
    const parsed = JSON.parse(raw);
    return typeof parsed.version === "string" ? parsed.version : "0.1";
  } catch {
    return "0.1";
  }
}

function bump(versionStr) {
  const asNumber = Number.parseFloat(versionStr);
  const safeNumber = Number.isFinite(asNumber) ? asNumber : 0.1;
  // Round to 1 decimal place to avoid floating point drift (0.1 + 0.2 etc).
  const next = Math.round((safeNumber + 0.1) * 10) / 10;
  return next.toFixed(1);
}

const currentVersion = readVersion();
const nextVersion = noBump ? currentVersion : bump(currentVersion);

if (!noBump) {
  writeFileSync(versionFilePath, JSON.stringify({ version: nextVersion }, null, 2) + "\n");
}

mkdirSync(generatedDir, { recursive: true });
writeFileSync(
  generatedFilePath,
  `// This file is auto-generated by scripts/bump-version.mjs on every build.
// Do not edit by hand -- your changes will be overwritten.
export const APP_VERSION = "${nextVersion}";
`
);

console.log(
  `[bump-version] ${noBump ? "using" : "bumped to"} version ${nextVersion} (${generatedFilePath})`
);
